import Head from 'next/head'
import Map from '../components/Map'
import Header from '../components/Header'

export default function Home({ dummy }) {

  return (
    <div className="">
      <Head>
        <title>Delivery Tracking System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css' rel='stylesheet' />
      </Head>

      <Header />
      <Map />
    </div>
  )
}

export async function getServerSideProps(context) {
  // code to get vehicle name from get vehicle names request
  // var xhr = new XMLHttpRequest();
  // var url = "http://api-gateway:5000/api/vechicles";
  // xhr.open("GET", url, true);
  // xhr.setRequestHeader("Content-Type", "application/json");
  return {
    props: {}, // will be passed to the page component as props
  }
}