import Head from 'next/head'

export default function Home({dummy}) {

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <h1>hello!!</h1>
      </div>
    </div>
  )
}

export async function getServerSideProps(context) {
  var dummy = {"a":"b"}

  return {
    props: {dummy}, // will be passed to the page component as props
  }
}
