import Head from 'next/head'
import Map from '../components/Map'
import Header from '../components/Header'

export default function Home({ dummy }) {

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css' rel='stylesheet' />
      </Head>

      <Header />
      <Map dummy={dummy} />
    </div>
  )
}

export async function getServerSideProps(context) {

  var dummy =
  {
    "kafkaTopicName": "cargo-delivery-truck",
    "truckNumber": 27,
    "truckType": "Cargo Truck",
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "properties": {},
        "geometry": {
          "type": "LineString",
          "coordinates": [
            [
              72.9715347290039,
              19.1967292074432
            ],
            [
              72.97256469726562,
              19.196242858212912
            ],
            [
              72.97325134277344,
              19.195756507545298
            ],
            [
              72.9741096496582,
              19.195756507545298
            ],
            [
              72.97548294067383,
              19.1955943903367
            ]
          ]
        }
      }
    ]
  }
  return {
    props: { dummy }, // will be passed to the page component as props
  }
}
