import Head from 'next/head'
import mapboxgl from 'mapbox-gl';
import {useEffect, useState} from 'react';

export default function Home() {

  const [pageIsMounted, setPageIsMounted] = useState(false)
  mapboxgl.accessToken = 'pk.eyJ1IjoiYnJheDI1MDciLCJhIjoiY2t4azgyOXBxNmRwaDJ1cTNjMGRqcjF3ZCJ9.0pJi--39nsT8km17AeiY3g';
  useEffect(() => {
    setPageIsMounted(true)
      const map = new mapboxgl.Map({
        container: 'my-map', // container ID
        style: 'mapbox://styles/brax2507/cl0gk3l6m003714p6cpgngplg/draft', // style URL
        center: [-74.5, 40], // starting position [lng, lat]
        zoom: 9 // starting zoom
      });
  }, [])

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css' rel='stylesheet' />
      </Head>

      <div className="h-screen max-w-screen-2xl mx-auto" id='my-map' />
      
    </div>
  )
}

export async function getServerSideProps(context) {
  var dummy = {"a":"b"}

  return {
    props: {dummy}, // will be passed to the page component as props
  }
}
